# Generated by Django 3.0.5 on 2020-04-26 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200426_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='claimed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_claimed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
