# Generated by Django 3.0.5 on 2020-04-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sms',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
