# Generated by Django 3.0.5 on 2020-05-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_ticket_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='label',
        ),
    ]
